name: 'Sbt Dependency Submission'
description: 'Submits the dependency graph of an sbt build to the Github Submission API'
author: 'The Scala Center'
branding:
  icon: 'package'
  color: '#1a84ac'
inputs:
  working-directory:
    description: "The relative path of the working directory of the sbt build."
    required: false
    default: ''
  modules-ignore:
    description: |
      A list of space-separated names of modules to ignore. The action will not resolve nor submit the dependencies of these modules.
      The name of a module contains the name of the project and its binary version.
      Example: `foo_2.13 bar_2.13`
    required: false
    default: ''
  token:
    description: GitHub Personal Access Token (PAT). Defaults to PAT provided by Action runner.
    required: false
    default: ${{ github.token }}
  sbt-plugin-version:
    description: Override the version of the sbt-github-dependency-submission plugin that is used internally."
    required: false
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
